#!/bin/bash
source ./library.sh || exit 1

CONFIG=`pwd`/config
[ -d "$CONFIG" ] || die "CONFIG does not exist or is not a file: $CONFIG"

function sync_to_target {
	target=$1
	shift
	echo "Syncing files with $target"
	path=`make_path "$target"`
	[ -n "$path" ] || die "No path found for target: $target"
	echo "Destination: $path"
	cd ~
	if [ "$target" = "portable" ]; then
		WINDOWS=true
	fi
	sync $* `cat $CONFIG/environment`
	sync $* .ssh --exclude=id_rsa
	if [ "$target" = "bluespot" ]; then
		path="$path/home/dafrito"
	fi
	sync $* --delete --max-delete=10 `cat $CONFIG/user`
}

if [ "$1" ]; then
	set -e
	sync_to_target $*
else
	for target in `all_targets`; do
		backup files $target || ERR=1
	done
fi
exit $ERR
