#!/bin/bash
source ./library.sh || exit 1

function push_one_to_git {
	local repo=$1
	local target=$2
	log "Pushing $repo to $target"
	case "$target" in
		github)
			case "$repo" in
				links|backup-settings) true ;; 
				*) push github 2>&1 || error "Failed to push to github" ;;
			esac
		;;
		unfuddle)
			case "$repo" in
				fritomod|riviera) push unfuddle ;;
			esac
		;;
		*)
			push_repo $target projects $repo || error "Backup failed: $repo"
		;;
	esac
}

function push_to_git {
	if [ -n "$2" ]; then
		push_one_to_git $2 $1
	else
		cd ~/projects
		for i in `ls`; do
			cd $i
			push_one_to_git $i $1
			cd ..
		done
	fi
}

cmd=${1-all}
shift
case "$cmd" in
	-private) 
		push_to_git unfuddle
		for repo in `all_targets`; do
			push_to_git $repo $*
		done ;;
	-public) push_to_git github $* ;;
	all) 
		backup git -public $* || error "Failed to push to public repos"
		backup git -private $* || error "Failed to push to private repos"
	;;
	*) push_to_git $cmd $*
esac
