#!/bin/bash
PATH=/bin:/usr/bin
[ -d "$BACKUP_EXECUTABLE_DIR" ] || BACKUP_EXECUTABLE_DIR=${0%/*}
source $BACKUP_EXECUTABLE_DIR/library.sh || exit 1
source $BACKUP_EXECUTABLE_DIR/load-settings.sh || exit 1

REPO_NAME=$1
[ -n "$REPO_NAME" ] || error "Repository name must be given";
shift
PROJECT={1-`pwd`}
PROJECT=${PROJECT##*/}
[ -n "$PROJECT" ] || error "Project name must be given";

DATA=`grep "^$REPO_NAME	" "$REPOS"` || error "Repository data could not be found: $REPO_NAME"
set - $DATA
shift
load_protocol $1
shift

protocol_load_settings $* || error "settings for repository $REPO_NAME failed to load";
[ "$DRY_RUN" ] && load_protocol dry
[ "$REPO_PATH" ] || error "repository $REPO_NAME must specify location";
log "Starting push to repository at '$REPO_PATH'"
set -o pipefail
if protocol_repo_exists "$REPO_PATH/$PROJECT"; then
	REPO_PATH=$REPO_PATH/$PROJECT
elif protocol_repo_exists "$REPO_PATH/$PROJECT.git"; then
	REPO_PATH=$REPO_PATH/$PROJECT.git
else
	REPO_PATH=$REPO_PATH/$PROJECT.git
	log "Creating new repository at '$REPO_PATH'"
	protocol_init_repo 2>&1 || error "failed to create repository at $REPO_PATH";
fi
log "Now pushing to '$REPO_PATH'"
protocol_push_repo 2>&1 || error "failed to push to repository at $REPO_PATH";
