#!/bin/bash
PATH=/bin:/usr/bin
[ -d "$BACKUP_EXECUTABLE_DIR" ] || BACKUP_EXECUTABLE_DIR=${0%/*}

source $BACKUP_EXECUTABLE_DIR/library.sh || exit 1
source $BACKUP_EXECUTABLE_DIR/load-settings.sh || exit 1

log "Time of start: `date`"
PROFILE=${1-full}
shift
cd $PROFILES
[ -f "$PROFILE" ] || error "backup: $PROFILE is not a valid profile"
log "Running profile '$PROFILE'"
export PATH=/bin:/usr/bin:$BACKUP_EXECUTABLE_DIR
export BACKUP_EXECUTABLE_DIR
bash ./"$PROFILE" $*
R=$?
if [ "$R" = "0" ]; then
	log "Profile '$PROFILE' was successful."
else
	log "Profile '$PROFILE' failed with error code: $R"
fi
log "Time of completion: `date`"
exit $R
