#!/bin/bash

# Note that some functions are intentionally omitted

function protocol_init_repo {
	echo "git init to `protocol_canonicalize $*`"
}

function protocol_push_repo {
	echo "git push to `protocol_canonicalize $*`"
}
