#!/bin/bash

function protocol_load_settings {
	TARGET=`echo $1 | sed -re 's%[[:space:]]+%/%g'`
	shift
	while [ "$1" ]; do
		case "$1" in
			-*) protocol_load_global_args $* ;;
			*) TARGET="$TARGET/$1"
		esac
		shift
	done
}

function protocol_requires_internet {
	false
}

function protocol_repo_exists {
	local path=`protocol_canonicalize "$*"`
	[ -d "$path" ];
}

function protocol_canonicalize {
	readlink -m $TARGET/$*
}

function protocol_init_repo {
	git init --bare `protocol_canonicalize "$*"`
}

function protocol_push_repo {
	protocol_default_push --mirror `protocol_canonicalize "$*"`
}
