#!/bin/bash

function protocol_load_settings {
	TARGET_DIR=`echo $* | sed -re 's%[[:space:]]+%/%g'`
}

function protocol_repo_exists {
	local path=`protocol_canonicalize "$*"`
	[ -d "$path" ];
}

function protocol_canonicalize {
	readlink -m $TARGET_DIR/$*
}

function protocol_init_repo {
	git init --bare `protocol_canonicalize "$*"`
}

function protocol_push_repo {
	git push --mirror --porcelain `protocol_canonicalize "$*"`
}
