#!/bin/bash

function load_remote_repo {
	if [ "$BACKUP_PID" ]; then
		REMOTES="$TMP/remotes/$REPO_NAME";
		mkdir -p "$TMP/remotes"
	else
		REMOTES=/tmp/backup-ssh-remotes.$$/
		mkdir -p $REMOTES
		trap 'rm -rf "$REMOTES"' EXIT
		REMOTES=$REMOTES/$REPO_NAME
	fi
	if [ ! -e "$REMOTES" ]; then
		ssh -l "$SSH_USERNAME" "$SSH_URL" "find $REPO_PATH -maxdepth 1 -type d" >$REMOTES
	fi
}

function protocol_load_settings {
	SSH_URL=${1?"URL must be given for $REPO_NAME"};
	SSH_USERNAME=${2?"username must be given for $REPO_NAME"};
	REPO_PATH=${3?"remote path must be given for $REPO_NAME"};
}

function protocol_repo_exists {
	load_remote_repo
	grep -q -F "$REPO_PATH/$*" $REMOTES
}

function protocol_init_repo {
	ssh -l $SSH_USERNAME $SSH_URL "
		mkdir -p $REPO_PATH
		cd $REPO_PATH/"$*"
		git init --bare"
}

function protocol_canonicalize {
	echo "$SSH_USERNAME@$SSH_URL:$REPO_PATH/$*"
}

function protocol_push_repo {
	git push --mirror `protocol_canonicalize "$*"`
}
