#!/bin/bash

function protocol_load_settings {
	true
}

function protocol_repo_exists {
	git remote | grep -q "^$TARGET_NAME$"
}

function protocol_canonicalize {
	echo $TARGET_NAME
}

function protocol_init_repo {
	die "Cannot init a remote repository at $TARGET_NAME"
	# TODO: It's possible we could run 'git remote add' here, but I don't
	# like modifying original content unless absolutely necessary.
}

function protocol_push_repo {
	protocol_default_push `protocol_canonicalize "$*"`
}
